/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElText: typeof import('element-plus/es')['ElText']
    Header: typeof import('./src/components/Header.vue')['default']
    LogIn: typeof import('./src/components/LogIn.vue')['default']
    LogInDialog: typeof import('./src/components/LogIn.vue')['default']
    ProductItem: typeof import('./src/components/ProductItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShoppingCartItem: typeof import('./src/components/ShoppingCartItem.vue')['default']
    SignUp: typeof import('./src/components/SignUp.vue')['default']
    SignUpDialog: typeof import('./src/components/SignUp.vue')['default']
  }
}
